### ISSUE TITLE
Problem with UTF8

### ISSUE THREAD

**Issue by qznc** [michal-h21/rdfref#1]
I use ` \usepackage[utf8]{inputenc}`. Putting unicode into the object part of a triple seems to break it.

The error is `Missing \endcsname inserted.` for the following line in the aux file:

    \LoadTriple {crt:about}{pfl:crtname}{\UTFviii@two@octets Über Uns Seite}

**Comment by michal-h21** [comment]
Try to use `\AddPropertyEx` for objects which could contain macros. Diacritics are macros as well when you use `inputenc` package. Alternatively,  you can try to use Unicode engine, either LuaTeX or XeTeX.
