### ISSUE TITLE
TL 2024 make fails

### ISSUE THREAD

**Issue by ouboub** [michal-h21/rdfref#8]
Hi

After several months, I thought to give rdfref again a try.
I clone freshly and run make (using TL 2024)
but I received
```
/usr/share/texlive/texmf-dist/tex/generic/xstring/xstring.sty
(/usr/share/texlive/texmf-dist/tex/generic/xstring/xstring.tex))

! LaTeX Error: Command \SetProperty already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.31 }

```
any idea what is wrong?

Uwe Brauer

**Comment by michal-h21** [comment]
It seems that LaTeX now defines the `\SetProperty` command, which clashes with the `\SetProperty` from `rdfref`. I am afraid that I will have to rename the command.

**Comment by michal-h21** [comment]
I've renamed `\SetProperty` to `\AssignProperty` to fix the clash with LaTeX core. If you use `\SetProperty` somewhere in your code, you will need to rename it too.

**Comment by ouboub** [comment]
>>> "MH" == Michal Hoftich ***@***.***> writes:

> I've renamed `\SetProperty` to `\AssignProperty` to fix the clash with
> LaTeX core. If you use `\SetProperty` somewhere in your code, you will
> need to rename it too.
Thanks!

I pulled, I run make
but now the file 

 0 Oct 27 14:33 theorems-sample.dot

Is empty after running make
-- 
I strongly condemn Hamas heinous despicable pogroms/atrocities on Israel
I strongly condemn Putin's war of aggression against Ukraine.
I support to deliver weapons to Ukraine's military. 
I support the EU and NATO membership of Ukraine.

**Comment by michal-h21** [comment]
I see. It seems that this wasn't caused by this change, but by this one: https://github.com/michal-h21/rdfref/commit/1e18aa0f2eddd858c6ead59d79023f72adfbd4c2 It should work now.

**Comment by ouboub** [comment]
> I see. It seems that this wasn't caused by this change, but by this one: [1e18aa0](https://github.com/michal-h21/rdfref/commit/1e18aa0f2eddd858c6ead59d79023f72adfbd4c2) It should work now.

confirmed this works now. thanks
